In [110]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVR

import matplotlib.pyplot as plt
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.metrics import r2_score

from sklearn.model_selection import GridSearchCV
import seaborn as sns
from sklearn.svm import LinearSVR

In [111]:
filepath = 'Datasets/Kaggle Cleaned/Life Expectancy Kaggle Transformed_1.csv'
df = pd.read_csv(filepath)
df.head(5)


Country  Year  Life expectancy  Adult mortality  Infant deaths  \
0  Afghanistan  2000             54.8            321.0       2.534276   
1  Afghanistan  2001             55.3            316.0       2.534276   
2  Afghanistan  2002             56.2              3.0       2.534276   
3  Afghanistan  2003             56.7            295.0       2.531065   
4  Afghanistan  2004             57.0            293.0       2.531065   

   Alcohol  Percentage expenditure  Hepatitis B   Measles   BMI  Polio  \
0     0.01                2.480898         62.0  5.475359  12.2   24.0   
1     0.01                2.496863         63.0  5.578042  12.6   35.0   
2     0.01                3.026871         64.0  5.111467  13.0   36.0   
3     0.01                2.550095         65.0  4.626970  13.4   41.0   
4     0.02                2.913820         67.0  4.374016  13.8    5.0   

   Total expenditure  Diphtheria  HIV/AIDS  Thinness 1-19 years  \
0               8.20        24.0 -0.827814                  2.3   
1               7.80        33.0 -0.827814                  2.1   
2               7.76        36.0 -0.827814                 19.9   
3               8.82        41.0 -0.827814                 19.7   
4               8.79         5.0 -0.827814                 19.5   

   Income composition of resources  Schooling  
0                            0.338        5.5  
1                            0.340        5.9  
2                            0.341        6.2  
3                            0.373        6.5  
4                            0.381        6.8

In [112]:
df.shape

(2445, 17)

In [113]:
df.describe()

Year  Life expectancy  Adult mortality  Infant deaths  \
count  2445.000000      2445.000000      2445.000000    2445.000000   
mean   2007.000000        68.795051       166.644581       1.053562   
std       4.321378         9.260263       125.082974       0.994150   
min    2000.000000        36.300000         1.000000       0.000000   
25%    2003.000000        63.000000        76.000000       0.000000   
50%    2007.000000        71.800000       146.000000       0.943791   
75%    2011.000000        75.000000       227.000000       2.017589   
max    2014.000000        89.000000       723.000000       3.102930   

           Alcohol  Percentage expenditure  Hepatitis B      Measles  \
count  2445.000000             2445.000000  2445.000000  2445.000000   
mean      4.309732                5.003168    75.975869     2.310691   
std       3.937997                3.000241    28.413085     2.123543   
min       0.010000               -2.181280     2.000000     0.000000   
25%       0.680000                3.017851    67.000000     0.000000   
50%       3.410000                5.032074    89.000000     2.365712   
75%       7.170000                7.160764    96.000000     4.237018   
max      17.870000               12.587254    99.000000     6.491184   

               BMI        Polio  Total expenditure   Diphtheria      HIV/AIDS  \
count  2445.000000  2445.000000        2445.000000  2445.000000  2.445000e+03   
mean     37.669816    82.087117           5.769072    81.998364 -4.940379e-17   
std      19.778206    23.469941           2.307287    23.702742  1.000205e+00   
min       1.000000     3.000000           0.370000     2.000000 -8.278139e-01   
25%      18.800000    77.000000           4.240000    78.000000 -8.278139e-01   
50%      42.700000    92.000000           5.620000    92.000000 -8.278139e-01   
75%      55.500000    97.000000           7.200000    97.000000  1.246853e+00   
max      77.100000    99.000000          14.390000    99.000000  1.305011e+00   

       Thinness 1-19 years  Income composition of resources    Schooling  
count          2445.000000                      2445.000000  2445.000000  
mean              5.084172                         0.614865    11.815174  
std               4.531485                         0.207476     3.162035  
min               0.100000                         0.000000     0.000000  
25%               1.700000                         0.487000    10.000000  
50%               3.500000                         0.666000    12.200000  
75%               7.400000                         0.760000    13.900000  
max              27.700000                         0.936000    20.700000

In [114]:
X = df.drop(['Year', 'Country', 'Life expectancy'], axis=1)  # Features
y = df['Life expectancy'] #target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [115]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X_train



array([[-0.7373628 , -1.0641457 ,  1.96574664, ..., -0.74562111,
         1.19545595,  1.03884925],
       [-0.11514297,  1.3224295 ,  0.82070943, ..., -0.48067994,
         0.49459412,  0.62961195],
       [-1.04847272,  0.99296048,  1.50057527, ..., -0.48067994,
         0.46144525,  0.09445547],
       ...,
       [ 1.00166186,  0.50586767,  0.67246801, ..., -0.59107209,
         0.59404073,  0.66109174],
       [-1.15217602, -1.0641457 ,  1.9913055 , ..., -0.43652308,
         0.85449614,  1.41660676],
       [ 1.01761621,  1.23014967, -0.71793431, ...,  0.66739845,
        -0.53302086, -1.16473623]])

In [116]:
from sklearn.decomposition import PCA
pca = PCA(n_components=0.9)
pca_data = pca.fit(X_train)
pca_data.explained_variance_ratio_

array([0.37397486, 0.11359385, 0.08566948, 0.07593674, 0.05953555,
       0.05026926, 0.04469398, 0.03750436, 0.03661629, 0.03433182])

In [117]:
np.cumsum(np.round(pca_data.explained_variance_ratio_, decimals = 4) * 100)

array([37.4 , 48.76, 57.33, 64.92, 70.87, 75.9 , 80.37, 84.12, 87.78,
       91.21])

In [118]:
X_train = pca.transform(X_train)
X_test = pca.transform(X_test)
X_train.shape

(1956, 10)

In [119]:

for i in ['linear','poly','rbf']:
    ker = SVR(kernel = i, gamma = 'auto')
    ker.fit(X_train, y_train)
    ker_train= ker.score(X_train,y_train)
    ker_test = ker.score(X_test, y_test)
    print('For the', i,'kernel, the train score is: {:.4f}'.format(ker_train))
    print('For the', i,'kernel, the test score is: {:.4f}'.format(ker_test))
    print('\n')

For the linear kernel, the train score is: 0.7618
For the linear kernel, the test score is: 0.7612


For the poly kernel, the train score is: 0.8435
For the poly kernel, the test score is: 0.8115


For the rbf kernel, the train score is: 0.8795
For the rbf kernel, the test score is: 0.8585




# SVM with Kernel Linear

In [120]:

#We are considering only the two main parameters- C and gamma
param_grid = {'C': [0.001, 0.01, 0.1, 1, 10, 100],
              'gamma': [0.001, 0.01, 0.1, 1, 10, 100],
              'epsilon': [0.01, 0.1, 0.5, 1.0, 2.0]}
print("Parameter grid:\n{}".format(param_grid))

grid_ker_lin = GridSearchCV(SVR(kernel = 'linear'), param_grid, cv = 5, return_train_score=True)
grid_ker_lin.fit(X_train,y_train)

print("Best parameters for kernel SVR linear: {}".format(grid_ker_lin.best_params_))
print("Best cross-validationscore: {:.2f}".format(grid_ker_lin.best_score_))

Parameter grid:
{'C': [0.001, 0.01, 0.1, 1, 10, 100], 'gamma': [0.001, 0.01, 0.1, 1, 10, 100], 'epsilon': [0.01, 0.1, 0.5, 1.0, 2.0]}
Best parameters for kernel SVR linear: {'C': 0.1, 'epsilon': 2.0, 'gamma': 0.001}
Best cross-validationscore: 0.78


In [121]:
best_kerlinsvr = SVR( kernel = 'linear', C=0.1, gamma=0.001, epsilon = 2.0)
best_kerlinsvr.fit(X_train, y_train)
ykerlinsvr_predicted = best_kerlinsvr.predict(X_test)

print('Train score: {:.4f}'.format(best_kerlinsvr.score(X_train, y_train)))
print('Test score: {:.4f}'.format(best_kerlinsvr.score(X_test, y_test)))
print('R2_score: {:.4f}'.format(r2_score(y_test,ykerlinsvr_predicted)))
MSE = np.square(np.subtract(y_test,ykerlinsvr_predicted)).mean()
print('MSE: {:.4f}'.format(MSE))
RMSE = np.sqrt(mean_squared_error(y_test, ykerlinsvr_predicted))
print('RMSE: {:.4f}'.format(RMSE))

Train score: 0.7783
Test score: 0.7832
R2_score: 0.7832
MSE: 19.3147
RMSE: 4.3949


In [102]:
from sklearn.model_selection import cross_val_score


# Khởi tạo mô hình SVR
svr = SVR(kernel='linear', C=0.1, epsilon=2.0, gamma = 0.001)

# Sử dụng cross-validation với 5 folds
scores = cross_val_score(svr, X_train, y_train, cv=5, scoring='neg_mean_squared_error')

# Chuyển đổi từ MSE sang RMSE và tính trung bình
rmse_scores = np.sqrt(-scores)
mean_rmse = np.mean(rmse_scores)

print("Cross-Validation RMSE scores:", rmse_scores)
print("Mean RMSE:", mean_rmse)


Cross-Validation RMSE scores: [3.78304471 3.83361762 3.75132962 3.92978226 3.77521671]
Mean RMSE: 3.8145981817702337


In [103]:
# Khởi tạo mô hình SVR
svr = SVR(kernel='linear', C=0.1, epsilon=2.0, gamma=0.001)

# Sử dụng cross-validation với 5 folds để tính R² scores
r2_scores = cross_val_score(svr, X_train, y_train, cv=5, scoring='r2')

# Tính trung bình và độ lệch chuẩn của R² scores
mean_r2 = np.mean(r2_scores)
std_r2 = np.std(r2_scores)

print("Cross-Validation R² scores:", r2_scores)
print("Mean R² score:", mean_r2)


Cross-Validation R² scores: [0.82417358 0.82045719 0.83565312 0.83298748 0.8264304 ]
Mean R² score: 0.827940352712995


# SVR with Kernel Poly (impossible to run this model)

# SVR with Kernel RBF

In [104]:
#We are considering only the two main parameters- C and gamma
param_grid = {'C': [0.001, 0.01, 0.1, 1, 10, 100],
              'gamma': [0.001, 0.01, 0.1, 1, 10, 100],
              'epsilon': [0.01, 0.1, 0.5, 1.0, 2.0]}

grid_ker_rbf = GridSearchCV(SVR(kernel = 'rbf'), param_grid, cv = 7, return_train_score=True)
grid_ker_rbf.fit(X_train,y_train)

print("Best parameters for kernel rbf: {}".format(grid_ker_rbf.best_params_))
print("Best cross-validationscore: {:.2f}".format(grid_ker_rbf.best_score_))
print('Train score: {:.4f}'.format(grid_ker_rbf.score(X_train, y_train)))
print('Test score: {:.4f}'.format(grid_ker_rbf.score(X_test, y_test)))

Best parameters for kernel rbf: {'C': 100, 'epsilon': 1.0, 'gamma': 0.1}
Best cross-validationscore: 0.91
Train score: 0.9723
Test score: 0.9212


In [109]:
best_kerrbfsvr = SVR( kernel = 'rbf', C=100, gamma=0.1, epsilon=1.0)
best_kerrbfsvr.fit(X_train, y_train)
ykerrbfsvr_predicted = best_kerrbfsvr.predict(X_test)

print('R2_score: {:.4f}'.format(r2_score(y_test,ykerrbfsvr_predicted)))
MSE = np.square(np.subtract(y_test,ykerrbfsvr_predicted)).mean()
print('MSE: {:.4f}'.format(MSE))
RMSE = np.sqrt(mean_squared_error(y_test, ykerrbfsvr_predicted))
print('RMSE: {:.4f}'.format(RMSE))

R2_score: 0.9212
MSE: 7.0226
RMSE: 2.6500


In [88]:
from sklearn.model_selection import cross_val_score


# Khởi tạo mô hình SVR
svr = SVR(kernel='rbf', C=100, epsilon=1.0, gamma=0.1)

# Sử dụng cross-validation với 5 folds
scores = cross_val_score(svr, X_train, y_train, cv=5, scoring='neg_mean_squared_error')

# Chuyển đổi từ MSE sang RMSE và tính trung bình
rmse_scores = np.sqrt(-scores)
mean_rmse = np.mean(rmse_scores)

print("Cross-Validation RMSE scores:", rmse_scores)
print("Mean RMSE:", mean_rmse)


Cross-Validation RMSE scores: [2.59022156 2.79601441 2.59617214 3.1585881  2.80293696]
Mean RMSE: 2.788786633907402


In [89]:
# Khởi tạo mô hình SVR
svr = SVR(kernel='rbf', C=100, epsilon=1.0, gamma=0.1)

# Sử dụng cross-validation với 5 folds để tính R² scores
r2_scores = cross_val_score(svr, X_train, y_train, cv=5, scoring='r2')

# Tính trung bình và độ lệch chuẩn của R² scores
mean_r2 = np.mean(r2_scores)
std_r2 = np.std(r2_scores)

print("Cross-Validation R² scores:", r2_scores)
print("Mean R² score:", mean_r2)


Cross-Validation R² scores: [0.91757195 0.90449431 0.92128491 0.89210581 0.90432102]
Mean R² score: 0.9079556004963047
